### ISSUE TITLE
Test improvements

### ISSUE THREAD

**Issue by zifeo** [metatypedev/ghjk#21]
- the installs folder should be persisted between restart so it can be cached (locally and in the github runner)
- how to run a specific test only?
- write a test for each os/shell combination to test the hooks
- should the test fail if there is an error in the ghjk logs?

**Comment by Yohe-Am** [comment]
@zifeo
1. There's actually not much to cache in the installs folder as each test is run in isolation and there's not a lot of setup beforehand. I.e. there isn't much to test if we cache the install.
    - For the local runner, (enabled using `$GHJK_TEST_E2E_TYPE=local` and used on macos runners), we use the `deno` bin on the system and thus share it's module cache. I suppose I can add a cache step on `DENO_DIR` in the runners but currently, it's very lightweight
    - For the docker based suite (enabled using `$GHJK_TEST_E2E_TYPE=docker` and used on ubuntu-latest runners), I've changed the `debian` based `deno` image to `alpine` to make it even more lightweight. We can add docker image caching if the tests get heavier but I don't expect that to happen. And yeah, most of the intermediate steps like pulling in the `deno` dependencies are cached for the e2e tests.
2. This is possible using `deno task test --filter filter`.  That task straights goes to the `deno test` command and the suite is built upon `Deno.test`.
3. WIP in #14. 
4. WIP in #14.

**Comment by zifeo** [comment]
@Yohe-Am 👍 
1. I thought more of caching the actual ports download, maybe this needs a micro "proxy" to work efficiently on local and docker test driver

**Comment by Yohe-Am** [comment]
> caching downloads

I'd been thinking about that myself. Nix demands that you provide a check sum of sorts for any network download. I considered this and the `donwloadUrls` helpers avail on the `GithubReleasePorts`. They were an aborted attempt in that direction after I the `asdf` edge case showed itself again. Maybe we can provide a Deno based curl tool that adheres to the interface or maybe there are environment vars we can set for actual curl but seemed like a best effort hack.

In the context of testing,same complications arise. Since the ports might use plethora of methods for their downloads, (curl, wget, aria2), we'll have to mess with iptables or something system specific like that to make sure they use the proxy. We also want to test that the addresses they're calling out are still valid.

**Comment by zifeo** [comment]
maybe there is an easy way with https://docs.deno.com/runtime/manual/basics/modules/proxies + https://gist.github.com/osy/30c5c96d7575efd1d2a2db5e3def0815 (no need to patch squid though, or use another local caching proxy like https://github.com/hauke96/tiny-http-proxy)
